name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Deploy to Server
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USERNAME }}
          APP_DIR: /home/ubuntu/E-Commerce
        run: |
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
          ssh $USER@$HOST << 'EOF'
            set -e

            APP_DIR="/home/ubuntu/E-Commerce"
            REPO_URL="https://github.com/Azamat-JS/E-Commerce.git"

            if [ ! -d "$APP_DIR" ]; then
              git clone $REPO_URL $APP_DIR
            else
              cd $APP_DIR
              git pull origin main
            fi

            cd $APP_DIR

            docker compose down
            docker compose build
            docker compose up -d --remove-orphans

            # Optional: restart pm2 or nginx if needed
          EOF
